In [1]:
import pandas as pd

In [9]:
df_07 = pd.read_csv('./0/7.csv', encoding='cp949', header = 1)
df_07

  특성별(1)        항목       전체  일반학급 완전통합  특수학급 시간제 운영  특수학급 전일제 운영      기타
0     전체  대상자수 (명)  93494.0    17300.0      72842.0       1709.0  1644.0
1     전체    비율 (%)    100.0       18.5         77.9          1.8     1.8
2      유  대상자수 (명)   4867.0      757.0       3764.0        258.0    88.0
3      유    비율 (%)    100.0       15.6         77.3          5.3     1.8
4      초  대상자수 (명)  46520.0     8649.0      37052.0        190.0   629.0
5      초    비율 (%)    100.0       18.6         79.6          0.4     1.4
6      중  대상자수 (명)  16430.0     3153.0      12718.0        292.0   268.0
7      중    비율 (%)    100.0       19.2         77.4          1.8     1.6
8      고  대상자수 (명)  25678.0     4740.0      19308.0        970.0   660.0
9      고    비율 (%)    100.0       18.5         75.2          3.8     2.6